# .bashrc

# ln -s $HOME/config/bash/bashrc $HOME/.bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

shopt -s histappend

export HISTFILESIZE=1000000
export HISTSIZE=100000

export HISTTIMEFORMAT='%F %T  '

bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

export TERM=screen-256color

# User specific aliases and functions

# ls
alias ls='ls --color=auto'
alias l='ls -l'
alias ll='ls -l'
alias la='ls -la'
alias lt='ls -lt'
alias lh='ls -lh'

# vim
alias vi='vim'

# git
alias gp="git pull --all"
alias gsu="git submodule update"
alias gd="git diff"
alias gs="git status"
alias gl="git log"
alias gc="git checkout"
alias ga="git add"

